#!/usr/bin/env python

import os 
import sys
import subprocess
import time
from datetime import datetime

from idle import get_idle_time
from database import Database

INTERVAL = 30
TSTAMP_STR = '%Y/%m/%d,%H:%M:%S'

def shell(cmd):
    runner = subprocess.Popen(cmd, shell=True,
             stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    return runner.communicate()[0][:-1]

def main():

    db = Database()
    last = datetime.now()
    while True:
        idle_time = get_idle_time()
        active_app = shell(os.path.join(os.getcwd(),'active'))

        now = datetime.now()

        if idle_time >= INTERVAL:
            db.add_interval(
                last.strftime(TSTAMP_STR), 
                now.strftime(TSTAMP_STR),
                True,
                active_app)
        else:
            db.add_interval(
                last.strftime(TSTAMP_STR), 
                now.strftime(TSTAMP_STR),
                False,
                active_app)

        last = now
        time.sleep(INTERVAL)
    
if __name__ == '__main__':
    main()
